[package]
name = "ngwallet"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { version = "1.1.0",features = ["keys-bip39"] }
bdk_electrum = { version = "0.21.0" , optional = true}
anyhow = "1.0.97"
redb = "2.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.26"
chrono = "0.4.40"
base64 = "0.22.1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[features]
envoy = ["dep:bdk_electrum", "bdk_wallet/rusqlite"]
