[package]
name = "ngwallet"
version = "0.1.0"
edition = "2024"

[dependencies]
bdk_wallet = { version = "1.1.0", features = ["rusqlite"] }
bdk_electrum = "0.21.0"
anyhow = "1.0.97"
flutter_rust_bridge = "=2.8.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }