[package]
name = "ngwallet"
version = "0.6.0"
edition = "2024"

[dependencies]
bdk_wallet = { version = "2.0.0-alpha.0", features = ["keys-bip39","test-utils"] }
bdk_electrum = { version = "0.22.0", optional = true }
anyhow = "1.0.97"
redb = "2.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4.26"
base64 = "0.22.1"
bip39 = { version = "2.1.0", features = ["rand"], optional = true }
minicbor-serde = { version = "0.4.1", features = ["alloc"] }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[features]
envoy = ["dep:bdk_electrum", "dep:bip39", "bdk_wallet/rusqlite"]

[patch.crates-io]
bdk_wallet = { git = "https://github.com/Foundation-Devices/bdk_wallet", rev = "646fc24237427f9c0a669411c5ac709910ba5be5" }
bdk_chain = { git = "https://github.com/Foundation-Devices/bdk-1", rev = "0a532f6bcb042edb192a2db2673e331e7189e00e" }
bdk_core = { git = "https://github.com/Foundation-Devices/bdk-1", rev = "0a532f6bcb042edb192a2db2673e331e7189e00e" }
bdk_electrum = { git = "https://github.com/Foundation-Devices/bdk-1", rev = "0a532f6bcb042edb192a2db2673e331e7189e00e" }



